import { Product } from '@/types';

export const products: Product[] = [
  // Filters
  {
    id: 'self-cleaning-filter',
    name: 'Self Cleaning Filter',
    slug: 'self-cleaning',
    category: 'Filters',
    categorySlug: 'filters',
    description: 'Automated self-cleaning filter systems with SS316/SS304 construction for continuous filtration operations.',
    shortDescription: 'Automated filtration systems with automatic cleaning mechanism',
    images: ['/assets/images/products/filters/self-cleaning-01.jpg'],
    specifications: {
      moc: ['SS316', 'SS304', 'MS'],
      lineSize: '1" NB TO 10" NB (FLANGE, BSP)',
      rating: '50, 100, 200 TO 500 MICRON',
      innerElement: 'WEDGE WIRE FILTER BASKET',
      type: 'AUTO/MANUAL',
    },
    applications: [
      'Water filtration',
      'Oil filtration',
      'Paint filtration',
      'Ink filtration',
      'Solvents',
      'Chemicals',
      'Viscose liquid',
    ],
    features: [
      'Automatic cleaning mechanism',
      'Continuous operation',
      'Low maintenance',
      'High efficiency',
    ],
  },
  {
    id: 'catalyst-carbon-filter',
    name: 'Catalyst/Carbon Filter',
    slug: 'catalyst-carbon',
    category: 'Filters',
    categorySlug: 'filters',
    description: 'Specialized filters for catalyst recovery, carbon filtration, and chemical processing applications.',
    shortDescription: 'Specialized filters for catalyst and carbon recovery',
    images: ['/assets/images/products/filters/catalyst-01.jpg'],
    specifications: {
      moc: ['SS316', 'SS304', 'MS'],
      lineSize: '1/2" NB TO 20" NB (FLANGE, BSP)',
      rating: '1.5, 10, 25, 50 MICRON',
      innerElement: 'SINTERED POWDER, PP/POLYESTER/SILK SLEEVES',
      configuration: 'SOE (Flange), BSP, NPT THREAD',
    },
    applications: [
      'Chemical processing',
      'Catalyst recovery',
      'Carbon filtration',
      'Edible oil',
      'Water treatment',
    ],
    features: [
      'High filtration efficiency',
      'Easy media replacement',
      'Various configurations',
      'Customizable sizes',
    ],
  },
  {
    id: 'filter-housings',
    name: 'Filter Housings',
    slug: 'housings',
    category: 'Filters',
    categorySlug: 'filters',
    description: 'Single and multi-cartridge filter housings in various materials and sizes for industrial applications.',
    shortDescription: 'Single and multi-cartridge filter housings',
    images: ['/assets/images/products/filters/housings-01.jpg'],
    specifications: {
      moc: ['SS 316L', 'SS316', 'SS304L', 'SS304', 'MS', 'PP', 'UPVC', 'MSRL', 'PTFE COATING'],
      lineSize: '1/4" NB TO 20" NB',
      connectionType: 'BSP(F), NPT(F) THREADS, FLANGE 150#, TABLE E, TABLE F',
      hydroTestPressure: 'UPTO 100 KG/CM2',
      flowRate: '1000 M3/HR',
      design: 'CUSTOMISED (AS PER CUSTOMER REQUIREMENT)',
      type: 'JACKETED/NON-JACKETED',
    },
    applications: [
      'Water filtration',
      'Chemical filtration',
      'Pharmaceutical',
      'Food & Beverage',
      'Oil & Gas',
    ],
    features: [
      'Single and multi-cartridge options',
      'Various materials available',
      'High pressure rating',
      'Customizable design',
    ],
  },
  {
    id: 'duplex-housings',
    name: 'Duplex Housings & Strainers',
    slug: 'duplex-housings',
    category: 'Filters',
    categorySlug: 'filters',
    description: 'Duplex filter housings with 3-way ball valve or butterfly valve for continuous operation without downtime.',
    shortDescription: 'Duplex filter housings for continuous operation',
    images: ['/assets/images/products/filters/duplex-01.jpg'],
    specifications: {
      moc: ['SS316L', 'SS316', 'SS304L', 'SS304', 'MS', 'PP'],
      lineSize: '1/4" NB TO 20" NB',
      connectionType: 'BSP(F), NPT(F) THREADS, FLANGE 150#, TABLE E, TABLE F',
      hydroTestPressure: 'UPTO 100 KG/CM2',
      design: 'CUSTOMISED (AS PER CUSTOMER REQUIREMENT)',
      valves: '3-WAY BALL VALVE OR BUTTERFLY VALVE WITH TEE',
    },
    applications: [
      'Continuous filtration',
      'Process industries',
      'Chemical processing',
      'Water treatment',
    ],
    features: [
      'Zero downtime operation',
      'Easy switching between filters',
      'High reliability',
      'Customizable valves',
    ],
  },
  {
    id: 'strainers',
    name: 'Strainers',
    slug: 'strainers',
    category: 'Filters',
    categorySlug: 'filters',
    description: 'Y-type, T-type, and bucket type strainers for pipeline protection and coarse filtration.',
    shortDescription: 'Y-type, T-type, and bucket type strainers',
    images: ['/assets/images/products/filters/strainers-01.jpg'],
    specifications: {
      moc: ['SS316L', 'SS316', 'SS304L', 'SS304', 'MS'],
      variant: 'CASTED/ FABRICATED',
      type: 'Y TYPE, T TYPE & BUCKET TYPE',
      lineSize: '1/4" NB TO 20" NB',
      connectionType: 'BSP(F), NPT(F) THREADS, FLANGE 150#, TABLE E, TABLE F',
      hydroTestPressure: 'UPTO 100 KG/CM2',
      design: 'CUSTOMISED (AS PER CUSTOMER REQUIREMENT)',
      filterRating: '500 MESH TO 1 MESH',
    },
    applications: [
      'Pipeline protection',
      'Coarse filtration',
      'Pre-filtration',
      'Debris removal',
    ],
    features: [
      'Multiple types available',
      'Easy maintenance',
      'High flow capacity',
      'Durable construction',
    ],
  },
  {
    id: 'filter-cartridges',
    name: 'Filter Cartridges',
    slug: 'cartridges',
    category: 'Filters',
    categorySlug: 'filters',
    description: 'Disposable and cleanable filter cartridges in various materials and micron ratings.',
    shortDescription: 'Disposable and cleanable filter cartridges',
    images: ['/assets/images/products/filters/cartridges-01.jpg'],
    specifications: {
      size: '5", 10", 20", 30", 40" & CUSTOMISED',
      outerDiameter: 'STD & CUSTOMISED',
      innerDiameter: '20 MM TO CUSTOMISED',
      micronRating: '0.45, 1, 5, 10, 20, 25, 50, 100, 150, 200',
      configuration: 'DOE, SOE, CODE-7 & CUSTOMISED',
      media: ['SS WIRE MESH', 'SINTERED', 'CELLULOSE PAPER', 'SPUN BONDED', 'GLASS FIBER'],
      type: 'CYLINDRICAL & PLEATED',
      construction: 'ADHESIVE JOINT, WELDED',
    },
    applications: [
      'Liquid filtration',
      'Air filtration',
      'Hydraulic oil',
      'Chemical processing',
    ],
    features: [
      'Wide range of sizes',
      'Various materials',
      'High efficiency',
      'Reusable options',
    ],
  },
  {
    id: 'filter-bags',
    name: 'Filter Bags',
    slug: 'bags',
    category: 'Filters',
    categorySlug: 'filters',
    description: 'Filter bags in various sizes, materials, and configurations for liquid and air filtration.',
    shortDescription: 'Filter bags for liquid and air filtration',
    images: ['/assets/images/products/filters/bags-01.jpg'],
    specifications: {
      size: '10", 16", 20", 32" and CUSTOMISED',
      micronRating: '1, 5, 10, 20, 25, 50, 75, 100',
      configuration: 'WELDED, STITCHED',
      media: ['WOVEN & NON-WOVEN'],
      moc: ['POLYPROPYLENE', 'POLYESTER', 'NYLON', 'PC SATIN', 'ANTISTATIC'],
    },
    applications: [
      'Liquid filtration',
      'FBD/FBP filtration',
      'Vent bags',
      'Centrifugal filtration',
      'Vacuum transfer',
    ],
    features: [
      'Various sizes',
      'Multiple materials',
      'High capacity',
      'Cost-effective',
    ],
  },
  // Tanks & Vessels
  {
    id: 'pressure-vessels',
    name: 'Pressure Vessels',
    slug: 'pressure-vessels',
    category: 'Tanks & Vessels',
    categorySlug: 'tanks-vessels',
    description: 'High-quality pressure vessels manufactured to ASME standards for industrial applications.',
    shortDescription: 'ASME standard pressure vessels',
    images: ['/assets/images/products/tanks/pressure-vessel-01.jpg'],
    specifications: {
      moc: ['SS316', 'SS304', 'MS'],
      design: 'AS PER ASME STANDARDS',
      pressure: 'CUSTOMISED AS PER REQUIREMENT',
    },
    applications: [
      'Chemical processing',
      'Pharmaceutical',
      'Petrochemical',
      'Food & Beverage',
    ],
    features: [
      'ASME certified',
      'Custom designs',
      'High pressure rating',
      'Quality construction',
    ],
  },
  {
    id: 'reactor-tanks',
    name: 'Industrial Reactor Tanks',
    slug: 'reactor-tanks',
    category: 'Tanks & Vessels',
    categorySlug: 'tanks-vessels',
    description: 'Industrial reactor tanks for chemical reactions, mixing, and processing applications.',
    shortDescription: 'Reactor tanks for chemical processing',
    images: ['/assets/images/products/tanks/reactor-01.jpg'],
    specifications: {
      moc: ['SS316', 'SS304', 'MS'],
      design: 'CUSTOMISED AS PER REQUIREMENT',
      capacity: 'VARIOUS CAPACITIES AVAILABLE',
    },
    applications: [
      'Chemical reactions',
      'Mixing operations',
      'Pharmaceutical processing',
      'Batch processing',
    ],
    features: [
      'Custom designs',
      'Various capacities',
      'Agitation options',
      'Temperature control',
    ],
  },
  {
    id: 'conical-storage-tanks',
    name: 'Conical Storage Tanks',
    slug: 'conical-storage',
    category: 'Tanks & Vessels',
    categorySlug: 'tanks-vessels',
    description: 'Conical bottom storage tanks for efficient material storage and complete discharge.',
    shortDescription: 'Conical storage tanks with easy discharge',
    images: ['/assets/images/products/tanks/conical-storage-01.jpg'],
    specifications: {
      moc: ['SS316', 'SS304', 'MS'],
      design: 'CUSTOMISED AS PER REQUIREMENT',
      capacity: 'VARIOUS CAPACITIES AVAILABLE',
    },
    applications: [
      'Material storage',
      'Bulk storage',
      'Food & Beverage',
      'Chemical storage',
    ],
    features: [
      'Complete discharge',
      'Easy cleaning',
      'Various capacities',
      'Custom designs',
    ],
  },
  {
    id: 'conical-vessels',
    name: 'Conical Vessels',
    slug: 'conical-vessels',
    category: 'Tanks & Vessels',
    categorySlug: 'tanks-vessels',
    description: 'Conical vessels for mixing, reaction, and storage applications with efficient discharge.',
    shortDescription: 'Conical vessels for mixing and storage',
    images: ['/assets/images/products/tanks/conical-vessel-01.jpg'],
    specifications: {
      moc: ['SS316', 'SS304', 'MS'],
      design: 'CUSTOMISED AS PER REQUIREMENT',
      capacity: 'VARIOUS CAPACITIES AVAILABLE',
    },
    applications: [
      'Mixing operations',
      'Chemical reactions',
      'Storage',
      'Fermentation',
    ],
    features: [
      'Efficient mixing',
      'Complete discharge',
      'Custom designs',
      'Various sizes',
    ],
  },
];

// Helper functions
export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((product) => product.categorySlug === categorySlug);
}

export function getProductBySlug(categorySlug: string, productSlug: string): Product | undefined {
  return products.find(
    (product) => product.categorySlug === categorySlug && product.slug === productSlug
  );
}

export function getAllCategories(): string[] {
  return Array.from(new Set(products.map((product) => product.category)));
}

